name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 1️⃣ Install dependency (termasuk dev) untuk testing
    - name: Install Dependencies
      run: composer install

    # 2️⃣ Generate app key (kalau belum ada)
    - name: Copy .env
      run: cp .env.example .env

    - name: Generate Key
      run: php artisan key:generate

    # 3️⃣ Jalankan testing
    - name: Run Tests
      run: php artisan test

    # 4️⃣ Deploy ke server (hanya jika test sukses)
    - name: SSH Deploy
      if: success()
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/project_noval

          # Maintenance mode
          php artisan down

          git pull origin main

          composer install --no-dev --optimize-autoloader

          php artisan migrate --force
          php artisan optimize

          # Kembali online
          php artisan up